export const axisTranslate = (input, Lang = 'en') => {
    let dict = {
		"Perpetrator victim relationship": "Отношения между преступником и жертвой",
		"Role of injured person in armed conflict": "Роль пострадавшего в вооруженном конфликте",
		"Role of the injured person": "Роль пострадавшего",
		"Gender of perpetrator": "Пол преступника",
		"Specific anatomy": "Частная анатомия",
		"Histopathology": "Гистопатология",
		"Temporal properties": "Временные характристики",
		"Course": "Течение болезни",
		"Counterpart": "Аналог",
		"Temporal pattern / onset": "Временной паттерн / начало", // в приложении Temporal pattern and onset
		"Temporal pattern and onset": "Временная картина и наступление",
		"Time in life": "Период жизни",
		"Severity": "Степень тяжести",
		"Has severity": "Имеется степень тяжести",
		"Has pupil reaction score": "Характеризуется балльной оценкой реакции зрачков на свет",
		"Has alternative severity 1": "Имеется альтернативная степень тяжести 1",
		"Has alternative severity 2": "Имеется альтернативная степень тяжести 2",
		"Has target": "Имеется цель",
		"Has action": "Имеются действия",
		"Has means": "Имеется средство",
		"Has g c s motor score": "Характеризуется балльной оценкой двигательной реакции по шкале комы Глазго",
		"Has g c s eye score": "Характеризуется балльной оценкой по шкале комы Глазго (открывание глаз)",
		"Has g c s verbal score": "Характеризуется балльной оценкой вербальной функции по шкале комы Глазго",
		"Causal properties": "Характерные особенности причин состояния",
		"Causality": "Причинность",
		"Infectious agent": "Возбудитель инфекции",
		"Chemical agent": "Химический агент",
		"Causing condition": "Вызывающее состояние",
		"Context of assault and maltreatment": "Контекст нападения и жестокого обращения",
		"Medication": "Лекарственное средство",
		"Mode of transport of the injured person": "Вид транспорта, на котором находился пострадавший",
		"Occupational descriptor": "Дескриптор рода занятий",
		"Mechanism of transport injury without counterpart": "Механизмы получения травмы в ходе транспортного происшествия без столкновения",
		"Has causing condition": "Имеется причинное нарушение",
		"Laterality": "Латеральность",
		"Relational": "Реляционное",
		"Regional": "Региональная",
		"Distribution": "Распределение",
		"Serotype": "Серотип",
		"Genomic and chromosomal anomaly": "Геномная и хромосомная аномалия",
		"Injury properties": "Характер травмы",
		"Type of injury": "Вид травмы",
		"Fracture properties": "Характер перелома",
		"Fracture subtype": "Подвид перелома",
		"Fracture open or closed": "Перелом открытый или закрытый",
		"Joint involvement in fracture": "Поражение сустава при переломе",
		"Burn properties": "Харатер ожога",
		"Extent of burn by body surface": "Степень ожога, определенная по площади поверхности тела",
		"Extent of full thickness burn by body surface": "Степень ожога с утратой всех слоев кожи, определяемая по площади поверхности тела",
		"Outcome of full thickness burn": "Исход ожога с утратой всех слоев кожи",
		"Duration of coma": "Продолжительность комы",
		"Level of consciousness": "Уровень сознания",
		"Pupil reaction score": "Оценка реакции зрачка",
		"GCS eye score": "Оценка по шкале комы Глазго для глаз",
		"GCS motor score": "Оценка по шкале комы Глазго для моторных функций",
		"GCS verbal score": "Оценка по шкале комы Глазго для речи",
		"Diagnosis confirmed by": "Диагноз подтвержден по",
		"Has manifestation": "Имеется проявление",
		"Associated with": "Связанное с",
		"Intent": "Умысел",
		"Mechanism of injury": "Механизм причинения травмы",
		"Object or substance producing injury": "Предмет или вещество, причинившие травму",
		"Activity when injured": "Занятие в момент получения травмы",
		"Occupational description": "Профессия",
		"Place of occurrence": "Место происшествия",
		"Alcohol use in injury": "Употребление алкоголя при получении травмы",
		"Psychoactive drug use in injury": "Употребление психотропных препаратов при травме",
		"Transport event descriptor": "Дескриптор транспортного события",
		"Aspects of assault and maltreatment": "Аспекты нападения и жестокого обращения",
		"Aspects of intentional self harm": "Аспекты, связанные с умышленным причинением себе вреда",
		"Aspects of intentional self-harm": "Аспекты, связанные с умышленным причинением себе вреда",
		"Aspects of armed conflict": "Аспекты вооруженного конфликта",
		"Type of legal intervention": "Тип правового вмешательства",
		"Sports activity descriptor": "Дескриптор спортивного занятия",
		"Target": "Цель",
		"Action": "Действие",
		"Means": "Средства",
		"ICHI extension codes axes": "Оси кодов расширений МКМВ (Международной классификации медицинских вмешательств)",
		"Assistive products": "Вспомогательные продукты (средства)",
		"Telehealth": "Телемедицина",
		"Additional target": "Дополнительный объект",
		"Topology": "Топология",
		"Quantifiers": "Количественные характеристики",
		"Essential pathology tests": "Основные патологоанатомические исследования",
		"Additional descriptive information": "Дополнительная информация",
		"Therapeutic products": "Терапевтические изделия",
		"Medicaments": "Медикаменты",
		"Specific anatomical detail": "Конкретная анатомическая локализация",
		"Has alternative severity1": "Имеется альтернативная степень тяжести 1",
		"Has alternative severity2": "Имеется альтернативная степень тяжести 2",
		"Has GCS Eye Score": "Характеризуется балльной оценкой по шкале комы Глазго (открывание глаз)",
		"Has GCS Motor Score": "Характеризуется балльной оценкой двигательной реакции по шкале комы Глазго",
		"Has GCS Verbal Score": "Характеризуется балльной оценкой вербальной функции по шкале комы Глазго",
    }

    if(dict.hasOwnProperty(input) && Lang === 'ru') {
        return dict[input]
    }  else {
        return input
    }
}

export default axisTranslate
