export default {"body":"custom-prefix_body_KGjf3W","container":"custom-prefix_container_KGjf3W","header":"custom-prefix_header_KGjf3W","icon":"custom-prefix_icon_KGjf3W","li":"custom-prefix_li_KGjf3W","paragraph":"custom-prefix_paragraph_KGjf3W","title":"custom-prefix_title_KGjf3W","titleHeader":"custom-prefix_titleHeader_KGjf3W","ul":"custom-prefix_ul_KGjf3W"} as const;
export const body = "custom-prefix_body_KGjf3W" as const;
export const container = "custom-prefix_container_KGjf3W" as const;
export const header = "custom-prefix_header_KGjf3W" as const;
export const icon = "custom-prefix_icon_KGjf3W" as const;
export const li = "custom-prefix_li_KGjf3W" as const;
export const paragraph = "custom-prefix_paragraph_KGjf3W" as const;
export const title = "custom-prefix_title_KGjf3W" as const;
export const titleHeader = "custom-prefix_titleHeader_KGjf3W" as const;
export const ul = "custom-prefix_ul_KGjf3W" as const;
