declare const ClassNames: {
  "axisContainer": string;
  "axisModalContainer": string;
  "axisTocHeader": string;
  "button": string;
  "childrenInputSearch": string;
  "container": string;
  "crossHelp": string;
  "detailsAgent": string;
  "detailsAgentInfo": string;
  "detailsAgentTitle": string;
  "detailsConnection": string;
  "detailsTitle": string;
  "detailsTitleLabel": string;
  "editor": string;
  "editorButton": string;
  "editorDescription": string;
  "editorItem": string;
  "editorItemChild": string;
  "editorItemChildSecond": string;
  "icon": string;
  "inputSearch": string;
  "search": string;
  "searchWrapper": string;
  "treeViews": string;
  "uri": string;
  "windowPostcoordination": string;
  "wrapperToc": string;
};
export default ClassNames;