export default {"editorButton":"custom-prefix_editorButton_Cjz7Cq","editorDescription":"custom-prefix_editorDescription_Cjz7Cq","editorItem":"custom-prefix_editorItem_Cjz7Cq","editorItemSecond":"custom-prefix_editorItemSecond_Cjz7Cq","itemAxisData":"custom-prefix_itemAxisData_Cjz7Cq","itemAxisDataSecond":"custom-prefix_itemAxisDataSecond_Cjz7Cq","itemAxisWarning":"custom-prefix_itemAxisWarning_Cjz7Cq","postCoordinationCode":"custom-prefix_postCoordinationCode_Cjz7Cq","postCoordinationCodeData":"custom-prefix_postCoordinationCodeData_Cjz7Cq","postCoordinationCodeItem":"custom-prefix_postCoordinationCodeItem_Cjz7Cq","postCoordinationCodeItemActive":"custom-prefix_postCoordinationCodeItemActive_Cjz7Cq","postCoordinationCodeTitle":"custom-prefix_postCoordinationCodeTitle_Cjz7Cq","postCoordinationCodeсonnection":"custom-prefix_postCoordinationCodeСonnection_Cjz7Cq","postCoordinationData":"custom-prefix_postCoordinationData_Cjz7Cq","postCoordinationHelp":"custom-prefix_postCoordinationHelp_Cjz7Cq","postCoordinationIcon":"custom-prefix_postCoordinationIcon_Cjz7Cq"} as const;
export const editorButton = "custom-prefix_editorButton_Cjz7Cq" as const;
export const editorDescription = "custom-prefix_editorDescription_Cjz7Cq" as const;
export const editorItem = "custom-prefix_editorItem_Cjz7Cq" as const;
export const editorItemSecond = "custom-prefix_editorItemSecond_Cjz7Cq" as const;
export const itemAxisData = "custom-prefix_itemAxisData_Cjz7Cq" as const;
export const itemAxisDataSecond = "custom-prefix_itemAxisDataSecond_Cjz7Cq" as const;
export const itemAxisWarning = "custom-prefix_itemAxisWarning_Cjz7Cq" as const;
export const postCoordinationCode = "custom-prefix_postCoordinationCode_Cjz7Cq" as const;
export const postCoordinationCodeData = "custom-prefix_postCoordinationCodeData_Cjz7Cq" as const;
export const postCoordinationCodeItem = "custom-prefix_postCoordinationCodeItem_Cjz7Cq" as const;
export const postCoordinationCodeItemActive = "custom-prefix_postCoordinationCodeItemActive_Cjz7Cq" as const;
export const postCoordinationCodeTitle = "custom-prefix_postCoordinationCodeTitle_Cjz7Cq" as const;
export const postCoordinationCodeсonnection = "custom-prefix_postCoordinationCodeСonnection_Cjz7Cq" as const;
export const postCoordinationData = "custom-prefix_postCoordinationData_Cjz7Cq" as const;
export const postCoordinationHelp = "custom-prefix_postCoordinationHelp_Cjz7Cq" as const;
export const postCoordinationIcon = "custom-prefix_postCoordinationIcon_Cjz7Cq" as const;
