export default {"actions":"custom-prefix_actions_AQw5lG","archive":"custom-prefix_archive_AQw5lG","cancel":"custom-prefix_cancel_AQw5lG","container":"custom-prefix_container_AQw5lG","download":"custom-prefix_download_AQw5lG","emptyList":"custom-prefix_emptyList_AQw5lG","item":"custom-prefix_item_AQw5lG","reason":"custom-prefix_reason_AQw5lG","report":"custom-prefix_report_AQw5lG","status":"custom-prefix_status_AQw5lG","subtitle":"custom-prefix_subtitle_AQw5lG","subtitleGreen":"custom-prefix_subtitleGreen_AQw5lG","title":"custom-prefix_title_AQw5lG"} as const;
export const actions = "custom-prefix_actions_AQw5lG" as const;
export const archive = "custom-prefix_archive_AQw5lG" as const;
export const cancel = "custom-prefix_cancel_AQw5lG" as const;
export const container = "custom-prefix_container_AQw5lG" as const;
export const download = "custom-prefix_download_AQw5lG" as const;
export const emptyList = "custom-prefix_emptyList_AQw5lG" as const;
export const item = "custom-prefix_item_AQw5lG" as const;
export const reason = "custom-prefix_reason_AQw5lG" as const;
export const report = "custom-prefix_report_AQw5lG" as const;
export const status = "custom-prefix_status_AQw5lG" as const;
export const subtitle = "custom-prefix_subtitle_AQw5lG" as const;
export const subtitleGreen = "custom-prefix_subtitleGreen_AQw5lG" as const;
export const title = "custom-prefix_title_AQw5lG" as const;
