export default {"closeFilter":"custom-prefix_closeFilter_ivFnCG","code":"custom-prefix_code_ivFnCG","container":"custom-prefix_container_ivFnCG","dis":"custom-prefix_dis_ivFnCG","filterTitle":"custom-prefix_filterTitle_ivFnCG","infoSearch":"custom-prefix_infoSearch_ivFnCG","infoSearchText":"custom-prefix_infoSearchText_ivFnCG","link":"custom-prefix_link_ivFnCG","marker":"custom-prefix_marker_ivFnCG","upBlock":"custom-prefix_upBlock_ivFnCG","word":"custom-prefix_word_ivFnCG","wrapper":"custom-prefix_wrapper_ivFnCG"} as const;
export const closeFilter = "custom-prefix_closeFilter_ivFnCG" as const;
export const code = "custom-prefix_code_ivFnCG" as const;
export const container = "custom-prefix_container_ivFnCG" as const;
export const dis = "custom-prefix_dis_ivFnCG" as const;
export const filterTitle = "custom-prefix_filterTitle_ivFnCG" as const;
export const infoSearch = "custom-prefix_infoSearch_ivFnCG" as const;
export const infoSearchText = "custom-prefix_infoSearchText_ivFnCG" as const;
export const link = "custom-prefix_link_ivFnCG" as const;
export const marker = "custom-prefix_marker_ivFnCG" as const;
export const upBlock = "custom-prefix_upBlock_ivFnCG" as const;
export const word = "custom-prefix_word_ivFnCG" as const;
export const wrapper = "custom-prefix_wrapper_ivFnCG" as const;
