export default {"body":"custom-prefix_body_WtMppq","container":"custom-prefix_container_WtMppq","header":"custom-prefix_header_WtMppq","icon":"custom-prefix_icon_WtMppq","li":"custom-prefix_li_WtMppq","paragraph":"custom-prefix_paragraph_WtMppq","title":"custom-prefix_title_WtMppq","titleHeader":"custom-prefix_titleHeader_WtMppq","ul":"custom-prefix_ul_WtMppq"} as const;
export const body = "custom-prefix_body_WtMppq" as const;
export const container = "custom-prefix_container_WtMppq" as const;
export const header = "custom-prefix_header_WtMppq" as const;
export const icon = "custom-prefix_icon_WtMppq" as const;
export const li = "custom-prefix_li_WtMppq" as const;
export const paragraph = "custom-prefix_paragraph_WtMppq" as const;
export const title = "custom-prefix_title_WtMppq" as const;
export const titleHeader = "custom-prefix_titleHeader_WtMppq" as const;
export const ul = "custom-prefix_ul_WtMppq" as const;
